config/routes.rb
Rails.application.routes.draw do
  # resources :payments
  resources :order_forms, only: [ :index ] do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: %i{registrations}
  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq) # monitoring console
  root "order_forms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :uuid             not null, primary key
#  comment       :text
#  email         :string
#  name          :string
#  phone         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  order_form_id :uuid             not null
#
# Indexes
#
#  index_orders_on_order_form_id  (order_form_id)
#
# Foreign Keys
#
#  fk_rails_...  (order_form_id => order_forms.id)
#
class Order < ApplicationRecord
  belongs_to :order_form
  has_many :order_lines, dependent: :destroy
  has_many :payments, dependent: :restrict_with_error
  has_paper_trail

  implicit_order_column = :created_at

  before_save :normalize_phone
  after_create :create_initial_payment

  validates :name, :email, :phone, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, phone: true
  validates_associated :order_lines

  accepts_nested_attributes_for :order_lines

  def phone(normalized: false)
    parsed = Phonelib.parse(super())
    if normalized
      parsed.full_e164
    else
      parsed.full_international
    end
  end

  def total_price
    order_lines.map(&:subtotal).sum
  end
  def total_amount
    order_lines.map(&:amount).sum
  end

  def total_paid
    payments.complete.sum(:amount)
  end

  def paid?
    total_paid >= total_price
  end

  private

  def normalize_phone
    self.phone = phone(normalized: true)
  end

  def create_initial_payment
    payments.wire_transfer.create!(reference: name)
  end
end

app/models/order_form.rb
# == Schema Information
#
# Table name: order_forms
#
#  id         :uuid             not null, primary key
#  closes_at  :datetime
#  iban       :string
#  opens_at   :datetime
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class OrderForm < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :products, dependent: :destroy
  has_rich_text :description
  has_rich_text :thanks
  has_paper_trail

  implicit_order_column = :closes_at
  scope :submittable, -> { where("opens_at < now() AND now() < closes_at") }

  accepts_nested_attributes_for :products

  validates :title, presence: true

  def is_open?
    DateTime.now.between? opens_at, closes_at
  end
  def is_closed?
    !is_open?
  end

  rails_admin do
    list do
      scopes [:submittable, nil]
      field :title
      field :opens_at
      field :closes_at
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :set_order_form, only: %i[ new create ]

  # GET /orders
  def index
    raise ActionController::RoutingError.new('Not Found')
  end

  # GET /orders/1
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new(order_form: @order_form)
    @order_form.products.each do |product|
      @order.order_lines.build(product: product, amount: 0)
    end
  end

  # GET /orders/1/edit
  def edit
    raise ActionController::RoutingError.new('Not Found')
  end

  # POST /orders
  def create
    @order = Order.new(order_params)
    @order.order_form = @order_form

    if @order_form.is_closed?
      redirect_to :root, alert: "This form has been closed"
    elsif @order.save
      redirect_to @order
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /orders/1
  def update
    raise ActionController::RoutingError.new('Not Found')
  end

  # DELETE /orders/1
  def destroy
    raise ActionController::RoutingError.new('Not Found')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order
        .includes(:order_form, :payments, order_lines: :product)
        .find(params[:id])
    end

    def set_order_form
      @order_form = OrderForm.find(params[:order_form_id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order)
        .permit(:order_form_id, :name, :email, :phone, :comment,
               order_lines_attributes: [:id, :product_id, :amount])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= bootstrap_form_with(model: [order_form, order], layout: :horizontal) do |form| %>

  <%= form.text_field :name %>
  <%= form.email_field :email %>
  <%= form.telephone_field :phone %>

  <%= form.form_group do %>
    <table class="table">
      <thead>
        <th><%= OrderLine.human_attribute_name :amount %></th>
        <th><%= OrderLine.human_attribute_name :product %></th>
        <th><%= OrderLine.human_attribute_name :unit_price %></th>
      </thead>
      <tbody>
        <%= form.fields_for :order_lines do |order_line_form| %>
          <% order_line = order_line_form.object %>
          <tr>
            <%= order_line_form.hidden_field :product_id %>
            <td><%= order_line_form.number_field :amount, min: 0, max: 10, hide_label: true %></td>
            <td><%= order_line.product.title %></td>
            <td>€<%= order_line.product.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <%= form.text_area :comment %>
  <%= form.form_group do %>
    <%= form.primary %>
  <% end %>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <%= order.order_form.thanks %>
  </p>

  <h3><%= t '.contact_information' %></h3>
  <address>
    <%= order.name %><br>
    <%= order.phone %><br>
    <%= order.email %>
  </address>

  <p>
    <h3><%= t '.order_contents' %></h3>
    <table class="table">
      <thead>
        <th scope="col"></th>
        <th scope="col"><%= OrderLine.human_attribute_name :amount %></th>
        <th scope="col"><%= OrderLine.human_attribute_name :product %></th>
        <th scope="col"><%= OrderLine.human_attribute_name :unit_price %></th>
        <th scope="col"><%= OrderLine.human_attribute_name :subtotal %></th>
      </thead>
      <tbody>
        <% for order_line in order.order_lines do %>
          <tr>
            <td></td>
            <td><%= order_line.amount %></td>
            <td><%= order_line.product.title %></td>
            <td>€<%= order_line.product.price %></td>
            <td>€<%= order_line.subtotal %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot class="table-group-divider">
        <tr>
          <td><%= t :total %></td>
          <td><%= order.total_amount %></td>
          <td colspan="2"></td>
          <td>€<%= order.total_price %></td>
        </tr>
      </tfoot>
    </table>
  </p>

  <% unless order.comment.blank? %>
    <h3><%= t '.comment' %></h3>
    <p>
      <%= order.comment %>
    </p>
  <% end %>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<% content_for :title, @order.order_form.title %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active"><%= @order.order_form.title %></li>
<% end %>
<hgroup>
  <h1><%= @order.order_form.title %> - <%= t '.new_order' %></h1>
  <p>
    <%= t '.closes_at', closing_time: l(@order.order_form.closes_at, format: :short) %>
  </p>
</hgroup>

<p>
  <%= @order.order_form.description %>
</p>

<%= render "form", order: @order, order_form: @order.order_form %>

app/views/orders/show.html.erb
<% content_for :title, @order.order_form.title %>

<hgroup>
  <h2><%= t '.order_title', form_title: @order.order_form.title %></h2>
  <p><%= link_to t('.permalink'), @order %></p>
</hgroup>

<% if @order.paid? %>
  <div class="alert alert-success d-flex align-items-center" role="alert">
    <%= t '.order_confirmed' %>
  </div>
<% else %>
  <div class="alert alert-warning d-flex align-items-center" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg"
         width="16"
         height="16"
         fill="currentColor"
         class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2"
         viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </svg>
    <%= t '.warning_order_unconfirmed' %>
  </div>
<% end %>

<%= render @order %>

<h3><%= t '.payment' %></h3>

<ul class="list-unstyled row row-cols-1 row-cols-md-2 g-4">
  <% @order.payments.not_cancelled.each do |payment| %>
    <li>
      <%= render payment %>
    </li>
  <% end %>
</ul>