config/routes.rb
Rails.application.routes.draw do
  # resources :payments
  resources :order_forms, only: [ :index ] do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: %i{registrations}
  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq) # monitoring console
  root "order_forms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/order_forms_controller.rb
class OrderFormsController < ApplicationController
  before_action :set_order_form, only: %i[ show edit update destroy ]

  # GET /order_forms
  def index
    @order_forms = OrderForm.submittable.order(closes_at: :asc)
  end

  # GET /order_forms/1
  def show
    raise ActionController::RoutingError.new('Not Found')
  end

  # GET /order_forms/new
  def new
    raise ActionController::RoutingError.new('Not Found')
  end

  # GET /order_forms/1/edit
  def edit
    raise ActionController::RoutingError.new('Not Found')
  end

  # POST /order_forms
  def create
    raise ActionController::RoutingError.new('Not Found')
  end

  # PATCH/PUT /order_forms/1
  def update
    raise ActionController::RoutingError.new('Not Found')
  end

  # DELETE /order_forms/1
  def destroy
    raise ActionController::RoutingError.new('Not Found')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_form
      @order_form = OrderForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_form_params
      params.fetch(:order_form, {})
    end
end

app/helpers/order_forms_helper.rb
module OrderFormsHelper
end

app/views/order_forms/_form.html.erb
<%= form_with(model: order_form) do |form| %>
  <% if order_form.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order_form.errors.count, "error") %> prohibited this order_form from being saved:</h2>

      <ul>
        <% order_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/order_forms/_order_form.html.erb
<div id="<%= dom_id order_form %>">
</div>

app/views/order_forms/edit.html.erb
<h1>Editing order form</h1>

<%= render "form", order_form: @order_form %>

<br>

<div>
  <%= link_to "Show this order form", @order_form %> |
  <%= link_to "Back to order forms", order_forms_path %>
</div>

app/views/order_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t '.order_forms' %></h1>

<ul id="order_forms" class="list-group list-group-flush">
  <% @order_forms.each do |order_form| %>
    <%= render order_form %>
    <li class="list-group-item">
      <%= link_to order_form.title, new_order_form_order_path(order_form) %>
      <em>
        <%= time_tag order_form.closes_at, title: order_form.closes_at do %>
          (<%= t '.open_for', time_distance: distance_of_time_in_words(DateTime.now, order_form.closes_at) %>)
        <% end %>
      </em>
    </li>
  <% end %>
</div>

app/views/order_forms/new.html.erb
<h1>New order form</h1>

<%= render "form", order_form: @order_form %>

<br>

<div>
  <%= link_to "Back to order forms", order_forms_path %>
</div>

app/views/order_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order_form %>

<div>
  <%= link_to "Edit this order form", edit_order_form_path(@order_form) %> |
  <%= link_to "Back to order forms", order_forms_path %>

  <%= button_to "Destroy this order form", @order_form, method: :delete %>
</div>